-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE STATUS = 'DONE' 
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3;

#SELECT USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES
#from USED_GOODS_BOARD as B
#inner join USED_GOODS_USER as U
#on B.WRITER_ID = U.USER_ID
#where STATUS = 'DONE'
#group by USER_ID
#having TOTAL_SALES >= 700000
#order by TOTAL_SALES