WITH PR AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT P.CATEGORY, P.MAX_PRICE, FD.PRODUCT_NAME
FROM PR AS P 
INNER JOIN FOOD_PRODUCT AS FD ON P.CATEGORY=FD.CATEGORY
AND P.MAX_PRICE = FD.PRICE
ORDER BY P.MAX_PRICE DESC;